import {
  THREED, TWOD, SCETCH, ANOTHER,
} from '../consts/galleriesNames';

const GalleriesDescription = [
  {
    name: TWOD,
    urls: [
      'https://i.imgur.com/hxbgzAT.jpg',
      'https://i.imgur.com/n40S530.jpg',
      'https://i.imgur.com/ewozWo0.jpg',
      'https://i.imgur.com/8fnYBBa.jpg',
      'https://i.imgur.com/jkT9kYq.jpg',
      'https://i.imgur.com/OqUMhFZ.png',
      'https://i.imgur.com/HDJmiat.jpg',
      'https://i.imgur.com/C4dDgr4.jpg',
      'https://i.imgur.com/sxAwdxv.jpg',
      'https://i.imgur.com/frVQBFY.jpg',
      'https://i.imgur.com/eIQvmwR.jpg',
      'https://i.imgur.com/Ke6AIFW.jpg',
      'https://i.imgur.com/HqNTAFa.jpg',
      'https://i.imgur.com/gp19Qsb.jpg',
      'https://i.imgur.com/IojlMCv.jpg',
      'https://i.imgur.com/vP2uThF.jpg',
      'https://i.imgur.com/dcvxOpW.jpg',
      'https://i.imgur.com/htPcmzw.png',
      'https://i.imgur.com/KCT7Qce.jpg',
      'https://i.imgur.com/nwn6OG6.jpg',
      'https://i.imgur.com/01ewsF4.jpg',
      'https://i.imgur.com/Oa7Y7SX.jpg',
    ],
    prevImg: 'https://i.imgur.com/frVQBFY.jpg',
    path: '/2D',
    title: 'twod',
  },
  {
    name: THREED,
    urls: [
      'https://i.imgur.com/hjGs3yj.jpg',
      'https://i.imgur.com/9rQopMl.jpg',
      'https://i.imgur.com/xTJVYAl.jpg',
      'https://i.imgur.com/VWW09Uu.jpg',
      'https://i.imgur.com/FsAXj7L.jpg',
      'https://i.imgur.com/M97u8VD.jpg',
      'https://i.imgur.com/ivCV0ow.jpg',
      'https://i.imgur.com/rb38eiM.jpg',
    ],
    prevImg: 'https://i.imgur.com/9rQopMl.jpg',
    path: '/3D',
    title: 'threed',
  },
  {
    name: SCETCH,
    urls: [
      'https://i.imgur.com/GtMwMCm.jpg',
      'https://i.imgur.com/rFEtieu.jpg',
      'https://i.imgur.com/to6e2rY.jpg',
      'https://i.imgur.com/wgczAdL.jpg',
      'https://i.imgur.com/2Dvljvl.jpg',
      'https://i.imgur.com/0csIw5b.jpg',
      'https://i.imgur.com/7A7xAza.jpg',
      'https://i.imgur.com/fc9myVO.jpg',
      'https://i.imgur.com/T78NIYX.jpg',
      'https://i.imgur.com/I2YFGBh.jpg',
      'https://i.imgur.com/G6nZ9QU.jpg',
      'https://i.imgur.com/GnzPtIX.jpg',
      'https://i.imgur.com/8qWHpk0.jpg',
      'https://i.imgur.com/mUf6B1I.jpg',
      'https://i.imgur.com/Mvr0ZeO.jpg',
      'https://i.imgur.com/KlnEAr9.jpg',
      'https://i.imgur.com/NrOB6st.jpg',
      'https://i.imgur.com/2OYV4Cp.jpg',
      'https://i.imgur.com/G9r7uTl.jpg',
      'https://i.imgur.com/inQ55Ab.jpg',
      'https://i.imgur.com/PHnmKZn.jpg',
      'https://i.imgur.com/yzoJyyI.jpg',
      'https://i.imgur.com/LrawWCx.jpg',
      'https://i.imgur.com/kTE9iiB.jpg',
      'https://i.imgur.com/fRuUHjJ.jpg',
      'https://i.imgur.com/6O4ZHBk.jpg',
      'https://i.imgur.com/iCIuTgy.jpg',
      'https://i.imgur.com/K092UyH.jpg',
      'https://i.imgur.com/ag9jS0V.jpg',
      'https://i.imgur.com/JUqaRvj.jpg',
      'https://i.imgur.com/pUswDhl.jpg',
      'https://i.imgur.com/WC0nQNz.jpg',
      'https://i.imgur.com/Pt67XQG.jpg',
      'https://i.imgur.com/mxoEYm9.jpg',
      'https://i.imgur.com/UYeUtaD.jpg',
      'https://i.imgur.com/ALyKHLR.jpg',
      'https://i.imgur.com/9ik9v7D.jpg',
      'https://i.imgur.com/4rFTO3s.jpg',
      'https://i.imgur.com/f6LcViI.jpg',
      'https://i.imgur.com/BH840HU.jpg',
      'https://i.imgur.com/8je4zNt.jpg',
      'https://i.imgur.com/Zs5rC6y.jpg',
      'https://i.imgur.com/eq96ePh.jpg',
      'https://i.imgur.com/Fr9oiLk.jpg',
      'https://i.imgur.com/8eA8EEG.jpg',
      'https://i.imgur.com/2ykFXqE.jpg',
      'https://i.imgur.com/mmUIrhg.jpg',
      'https://i.imgur.com/qIwoAcw.jpg',
    ],
    prevImg: 'https://i.imgur.com/UYeUtaD.jpg',
    path: '/scetch',
    title: 'Scetch',
  },
  {
    name: ANOTHER,
    urls: [
      'https://i.imgur.com/ZjMFutg.jpg',
      'https://i.imgur.com/25DMWQY.jpg',
      'https://i.imgur.com/2cZWmQl.jpg',
      'https://i.imgur.com/Lg4i0DS.png',
    ],
    prevImg: 'https://i.imgur.com/2cZWmQl.jpg',
    path: '/another',
    title: 'Another',
  },
];

export default GalleriesDescription;
