import {
  THREED, TWOD, SCETCH, ANOTHER,
} from '../consts/galleriesNames';

const GalleriesDescription = [
  {
    name: TWOD,
    urls: [
      'https://i.imgur.com/hxbgzAT.jpg',
      'https://i.imgur.com/n40S530.jpg',
      'https://i.imgur.com/ewozWo0.jpg',
      'https://i.imgur.com/8fnYBBa.jpg',
      'https://i.imgur.com/jkT9kYq.jpg',
      'https://i.imgur.com/OqUMhFZ.png',
      'https://i.imgur.com/HDJmiat.jpg',
      'https://i.imgur.com/C4dDgr4.jpg',
      'https://i.imgur.com/sxAwdxv.jpg',
      'https://i.imgur.com/frVQBFY.jpg',
      'https://i.imgur.com/eIQvmwR.jpg',
      'https://i.imgur.com/Ke6AIFW.jpg',
      'https://i.imgur.com/HqNTAFa.jpg',
      'https://i.imgur.com/gp19Qsb.jpg',
      'https://i.imgur.com/IojlMCv.jpg',
      'https://i.imgur.com/vP2uThF.jpg',
      'https://i.imgur.com/dcvxOpW.jpg',
      'https://i.imgur.com/htPcmzw.png',
      'https://i.imgur.com/KCT7Qce.jpg',
      'https://i.imgur.com/nwn6OG6.jpg',
      'https://i.imgur.com/01ewsF4.jpg',
      'https://i.imgur.com/Oa7Y7SX.jpg',
    ],
    prevImg: 'https://i.imgur.com/jkT9kYq.jpg',
    path: '/2D',
    title: 'twod',
  },
  {
    name: THREED,
    urls: [
      'https://i.imgur.com/RfZADlZ.jpg',
      'https://i.imgur.com/3sN3gKp.jpg',
      'https://i.imgur.com/tSy4FEs.jpg',
      'https://i.imgur.com/szrLKL1.jpg',
      'https://i.imgur.com/P294MGn.jpg',
      'https://i.imgur.com/JMwiEqT.jpg',
      'https://i.imgur.com/JMwiEqT.jpg',
      'https://i.imgur.com/JMwiEqT.jpg',
      'https://i.imgur.com/JMwiEqT.jpg',
      'https://i.imgur.com/JMwiEqT.jpg',
      'https://i.imgur.com/JMwiEqT.jpg',
    ],
    prevImg: 'https://i.imgur.com/frVQBFY.jpg',
    path: '/3D',
    title: 'threed',
  },
  {
    name: SCETCH,
    urls: [
      'https://i.imgur.com/hOqnnP8.jpg',
      'https://i.imgur.com/hOqnnP8.jpg',
      'https://i.imgur.com/hOqnnP8.jpg',
      'https://i.imgur.com/hOqnnP8.jpg',
      'https://i.imgur.com/hOqnnP8.jpg',
      'https://i.imgur.com/hOqnnP8.jpg',
      'https://i.imgur.com/hOqnnP8.jpg',
      'https://i.imgur.com/hOqnnP8.jpg',
      'https://i.imgur.com/hOqnnP8.jpg',
      'https://i.imgur.com/hOqnnP8.jpg',
      'https://i.imgur.com/hOqnnP8.jpg',
    ],
    prevImg: 'https://i.imgur.com/Ke6AIFW.jpg',
    path: '/scetch',
    title: 'Scetch',
  },
  {
    name: ANOTHER,
    urls: [
      'https://i.imgur.com/YnEGok4.jpg',
      'https://i.imgur.com/YnEGok4.jpg',
      'https://i.imgur.com/YnEGok4.jpg',
      'https://i.imgur.com/YnEGok4.jpg',
      'https://i.imgur.com/YnEGok4.jpg',
      'https://i.imgur.com/YnEGok4.jpg',
      'https://i.imgur.com/YnEGok4.jpg',
      'https://i.imgur.com/YnEGok4.jpg',
      'https://i.imgur.com/YnEGok4.jpg',
      'https://i.imgur.com/YnEGok4.jpg',
      'https://i.imgur.com/YnEGok4.jpg',
    ],
    prevImg: 'https://i.imgur.com/gp19Qsb.jpg',
    path: '/another',
    title: 'Another',
  },
];

export default GalleriesDescription;
